### ISSUE TITLE
Tagging a similar project

### ISSUE THREAD

**Issue by amchagas** [GliaX/faceshield#1]
Hi!
Sorry for the unwanted message here, but I thought it would be worth sharing the efforts being made from the folks at Prusa Research, as they are doing something similar and thinking about doing other tools for health workers (I'm guessing this is something you are already aware of, but in case not): 
https://blog.prusaprinters.org/from-design-to-mass-3d-printing-of-medical-shields-in-three-days/

**Comment by tareko** [comment]
Thank you for this. Unfortunately their project is currently not Free/Libre. A hospital cannot print their masks and use it, as almost any interpretation of CC-By-SA-NC excludes a hospital. I left a message on their prusaprinters page and happy if you have a better way to get in touch with them.

**Comment by kliment** [comment]
I have a direct contact there, @tareko please email me directly and I'll get you in touch. I strongly suspect they are willing to change the license to resolve that kind of issue.
