### ISSUE TITLE
is velcro acceptable instead of the printed buckle?

### ISSUE THREAD

**Issue by murtaugh** [GliaX/faceshield#11]

**Comment by tareko** [comment]
Yes, but it just adds a lot more processing. how do you attach the velcro? to where? I wouldn't support adding velcro to the strap as part of our reference design.

I'm closing this, but if I'm missing something and you have a proposal, please don't hesitate

tarek : )

**Comment by murtaugh** [comment]
I was just wondering. I will try it out and see how feasible it is. If it seems workable I'll bring it up again.
