### ISSUE TITLE
STL seem broken

### ISSUE THREAD

**Issue by MaxGiuliani** [GliaX/faceshield#12]
Downloaded the files, tried to open them in Meshmixer and Slic3R, neither software was able to load the models.

**Comment by AnimeEd** [comment]
Try this. I opened them up in solidworks and then resaved
[GliaSTL.zip](https://github.com/GliaX/faceshield/files/4364097/GliaSTL.zip)

**Comment by MaxGiuliani** [comment]
That worked, 

Thanks
