### ISSUE TITLE
Screen Size

### ISSUE THREAD

**Issue by amashari** [GliaX/faceshield#16]
@tareko I had a look at the sizing as you mentioned. I agree triming the height by 2cm makes sense (so from 250 to 230 mm). Width is fine at 280 mm. Would you like me to modify the repo?

**Comment by tareko** [comment]
Thank you Azad. I already did this in this commit: 333020f504ff3777e8f79f0b7b77bea991d7264d . Does that answer the need?

**Comment by amashari** [comment]
yes
