### ISSUE TITLE
Missing sheet.svg and mylar thickness

### ISSUE THREAD

**Issue by AnimeEd** [GliaX/faceshield#3]
Hi, I can't seem to find sheet.svg

Regarding the 5mil requirement, how critical is the thickness? Can 4mil and 6mil be used?

**Comment by tareko** [comment]
I haven't made sheet.svg yet. basically rounded rectangle.

As for plastic thickness, it's provider choice. We pick 0.125mm. Thicker is fine, but more expensive. I would suggest not going thinner.

**Comment by tareko** [comment]
Both of these are done in commit 725020ea147522c550765da6c42c1cf00f59d2e9 and c2495cfe5939bce9fe0edbc2ac0be2dfe354fd98
